apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
      - name: flask-app
        image: bakircuric/flask-app:latest
        ports:
        - containerPort: 5000
